/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(bae_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(26efa4c47f894ce27043e89e3bb6b701)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/bae_sink.h>
// pydoc.h is automatically generated in the build directory
#include <bae_sink_pydoc.h>

void bind_bae_sink(py::module& m)
{

    using bae_sink = ::gr::plasma::bae_sink;


    py::class_<bae_sink,
               gr::block,
               gr::basic_block,
               std::shared_ptr<bae_sink>>(
        m, "bae_sink", D(bae_sink))

        .def(py::init(&bae_sink::make),
             py::arg("samp_rate"),
             py::arg("ncol"),
             py::arg("center_freq"),
             py::arg("parent") = nullptr,
             D(bae_sink, make))


        .def("exec_", &bae_sink::exec_, D(bae_sink, exec_))


        .def(
            "qwidget",
            [](bae_sink& self) {
                return reinterpret_cast<uintptr_t>(self.qwidget());
            },
            D(bae_sink, qwidget))


        .def(
            "pyqwidget",
            [](std::shared_ptr<bae_sink> p) {
                return PyLong_AsLongLong(p->pyqwidget());
            },
            D(bae_sink, pyqwidget))


        .def("set_dynamic_range",
             &bae_sink::set_dynamic_range,
             py::arg("arg0"),
             D(bae_sink, set_dynamic_range))


        .def("set_msg_queue_depth",
             &bae_sink::set_msg_queue_depth,
             py::arg("depth"),
             D(bae_sink, set_msg_queue_depth))


        .def("set_metadata_keys",
             &bae_sink::set_metadata_keys,
             py::arg("samp_rate_key"),
             py::arg("n_matrix_col_key"),
             py::arg("center_freq_key"),
             py::arg("dynamic_range_key"),
             py::arg("prf_key"),
             py::arg("pulsewidth_key"),
             py::arg("detection_indices_key"),
             D(bae_sink, set_metadata_keys))

        ;
}