/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pluto_radar_bae.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d214b918d379c97e0d7d5afc01af0a46)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/pluto_radar_bae.h>
// pydoc.h is automatically generated in the build directory
#include <pluto_radar_bae_pydoc.h>

void bind_pluto_radar_bae(py::module& m)
{

    using pluto_radar_bae    = ::gr::plasma::pluto_radar_bae;


    py::class_<pluto_radar_bae, gr::block, gr::basic_block,
        std::shared_ptr<pluto_radar_bae>>(m, "pluto_radar_bae", D(pluto_radar_bae))

        .def(py::init(&pluto_radar_bae::make),
           py::arg("uri"),
           py::arg("frequency"),
           py::arg("samplerate"),
           py::arg("bandwidth"),
           py::arg("rx1_en"),
           py::arg("rx2_en"),
           py::arg("buffer_size"),
           py::arg("quadrature"),
           py::arg("rfdc"),
           py::arg("bbdc"),
           py::arg("gain1"),
           py::arg("gain1_value"),
           py::arg("gain2"),
           py::arg("gain2_value"),
           py::arg("rf_port_select"),
           py::arg("filter") = "",
           py::arg("auto_filter") = true,
           D(pluto_radar_bae,make)
        )
        




        
        .def("set_metadata_keys",
             &pluto_radar_bae::set_metadata_keys,
             py::arg("tx_freq_key"),
             py::arg("rx_freq_key"),
             py::arg("sample_start_key"),
             D(pluto_radar_bae, set_metadata_keys))

        ;




}
