/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(spectrum_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8aaff97037db58325bab4b28ec9a64b4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/spectrum_sink.h>
// pydoc.h is automatically generated in the build directory
#include <spectrum_sink_pydoc.h>

void bind_spectrum_sink(py::module& m)
{

    using spectrum_sink = ::gr::plasma::spectrum_sink;


    py::class_<spectrum_sink,
               gr::block,
               gr::basic_block,
               std::shared_ptr<spectrum_sink>>(
        m, "spectrum_sink", D(spectrum_sink))

        .def(py::init(&spectrum_sink::make),
             py::arg("samp_rate"),
             py::arg("ncol"),
             py::arg("center_freq"),
             py::arg("parent"),
             py::arg("mode"),
             D(spectrum_sink, make))


        .def("exec_", &spectrum_sink::exec_, D(spectrum_sink, exec_))


        .def(
            "qwidget",
            [](spectrum_sink& self) {
                return reinterpret_cast<uintptr_t>(self.qwidget());
            },
            D(spectrum_sink, qwidget))


        .def(
            "pyqwidget",
            [](std::shared_ptr<spectrum_sink> p) {
                return PyLong_AsLongLong(p->pyqwidget());
            },
            D(spectrum_sink, pyqwidget))


        .def("set_dynamic_range",
             &spectrum_sink::set_dynamic_range,
             py::arg("arg0"),
             D(spectrum_sink, set_dynamic_range))


        .def("set_msg_queue_depth",
             &spectrum_sink::set_msg_queue_depth,
             py::arg("depth"),
             D(spectrum_sink, set_msg_queue_depth))


        .def("set_metadata_keys",
             &spectrum_sink::set_metadata_keys,
             py::arg("samp_rate_key"),
             py::arg("n_matrix_col_key"),
             py::arg("center_freq_key"),
             py::arg("dynamic_range_key"),
             py::arg("prf_key"),
             py::arg("pulsewidth_key"),
             py::arg("detection_indices_key"),
             D(spectrum_sink, set_metadata_keys))

        ;
}