/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(spectro_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(706d43cbf5bfc4422f9dd9d0e6c012cb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/spectro_sink.h>
// pydoc.h is automatically generated in the build directory
#include <spectro_sink_pydoc.h>

void bind_spectro_sink(py::module& m)
{

    using spectro_sink = ::gr::plasma::spectro_sink;


    py::class_<spectro_sink,
               gr::block,
               gr::basic_block,
               std::shared_ptr<spectro_sink>>(m, "spectro_sink", D(spectro_sink))

        .def_static("make",
                    &spectro_sink::make,
                    py::arg("samp_rate"),
                    py::arg("fft_size"),
                    py::arg("ncol"),
                    py::arg("center_freq"),
                    py::arg("parent") = nullptr,
                    D(spectro_sink, make))

        .def(py::init(&spectro_sink::make),
             py::arg("samp_rate"),
             py::arg("fft_size"),
             py::arg("ncol"),
             py::arg("center_freq"),
             py::arg("parent"),
             D(spectro_sink, make))


        .def("exec_", &spectro_sink::exec_, D(spectro_sink, exec_))


        .def(
            "qwidget",
            [](spectro_sink& self) {
                return reinterpret_cast<uintptr_t>(self.qwidget());
            },
            D(spectro_sink, qwidget))


        .def(
            "pyqwidget",
            [](std::shared_ptr<spectro_sink> p) {
                return PyLong_AsLongLong(p->pyqwidget());
            },
            D(spectro_sink, pyqwidget))

        .def("set_msg_queue_depth",
             &spectro_sink::set_msg_queue_depth,
             py::arg("depth"),
             D(spectro_sink, set_msg_queue_depth))

        .def("set_update_time",
             &spectro_sink::set_update_time,
             py::arg("t"),
             D(spectro_sink, set_update_time))

        .def("set_metadata_keys",
             &spectro_sink::set_metadata_keys,
             py::arg("samp_rate_key"),
             py::arg("n_matrix_col_key"),
             py::arg("center_freq_key"),
             D(spectro_sink, set_metadata_keys));

        ;
}